### ISSUE TITLE
An error occurs when APP running

### ISSUE THREAD

**Issue by bbckorea** [NSTiwari/Gemma-on-Android#2]
**Question :** 
I am impressed with your project and find it very interesting.
However, after pushing the model(scigemma.bin) and build to Android Studio(modify InferenceModel.kt), upon running the app, it exits with the following log indicating it can't find the NDK library. Do you have any idea of the issues?

**Error Log :** 
`com.example.scigemma                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.scigemma, PID: 6624
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libllm_inference_engine_jni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1664)
                                                                                                    	at com.google.mediapipe.tasks.genai.llminference.LlmInference.<clinit>(LlmInference.java:27)
                                                                                                    	at com.google.mediapipe.tasks.genai.llminference.LlmInference.createFromOptions(LlmInference.java:33)
                                                                                                    	at com.example.scigemma.InferenceModel.<init>(InferenceModel.kt:36)
                                                                                                    	at com.example.scigemma.InferenceModel.<init>(Unknown Source:0)
                                                                                                    	at com.example.scigemma.InferenceModel$Companion.getInstance(InferenceModel.kt:51)
                                                                                                    	at com.example.scigemma.LoadingScreenKt$LoadingRoute$2$1.invokeSuspend(LoadingScreen.kt:43)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@a282039, androidx.compose.runtime.BroadcastFrameClock@1fd467e, StandaloneCoroutine{Cancelling}@7c597df, AndroidUiDispatcher@8e1cc2c]`

**Comment by NSTiwari** [comment]
Thanks for reporting. What mobile phone are you using to install the app? Could you detail its GPU specifications?

**Comment by bbckorea** [comment]
<img width="379" alt="device information" src="https://github.com/NSTiwari/Gemma-on-Android/assets/84180762/70a1d05b-b5e5-4037-9db4-95f685ffdef4">

**Here are the Android device specifications. Thanks**
